### ISSUE TITLE
-request_slow extension is ignored by the software

### ISSUE THREAD

**Issue by LudwigvonWu** [Syroot/CafiineServer#3]
Currently, when trying to use the `-request_slow` file extension in the data diredtory, the files are not requested by the server, while they are requested when just using the `-request` file extension.

USE CASE TO VERIFY THE BUG

Use the example [cited in the wiki](https://github.com/Syroot/CafiineServer/wiki/Dump-Folder), both using the `-request` extension and the `-request_slow` extension. If the file is missing in the dump directory, it will be requested only in the case of the -`request` extension.

**Comment by RayKoopa** [comment]
Yep, this seems to be a bug in this line https://github.com/Syroot/CafiineServer/blob/master/src/Syroot.CafiineServer/Client.cs#L160

_Someone_ missed a `-` character in the `request_slow` extension. Right now it would work if you omit the `-` and just append `request_slow` rather than `-request_slow`.

I'll fix the issue soon when I get back to this.

**Comment by RayKoopa** [comment]
Fixed with https://github.com/Syroot/CafiineServer/commit/80dd0f4b4b9b9bfcef5daa43467a22915df79d68
